config/routes.rb
Rails.application.routes.draw do
  resources :characters
  get 'static_pages/characters'

  get 'static_pages/about'

  get 'static_pages/index'

  root 'static_pages#index'

end

app/models/character.rb
class Character < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.all
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Character was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      params.require(:character).permit(:name, :level, :gender, :race, :profession, :description, :image_url)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @featured_characters = Character.where("level = '80'")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/characters/_form.html.erb
<%= form_for(@character) do |f| %>
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% @character.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.number_field :level %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.select(:gender, options_for_select([['Female', 'Female'], ['Male', 'Male']])) %>
  </div>
  <div class="field">
    <%= f.label :race %><br>
    <%= f.select(:race, options_for_select([['Asura', 'Asura'], ['Charr', 'Charr'], ['Human', 'Human'], ['Norn', 'Norn'], ['Sylvari', 'Sylvari']])) %>
  </div>
  <div class="field">
    <%= f.label :profession %><br>
    <%= f.select(:profession, options_for_select([['Elementalist', 'Elementalist'], ['Engineer', 'Engineer'], ['Guardian', 'Guardian'], ['Mesmer', 'Mesmer'], ['Necromancer', 'Necromancer'], ['Ranger', 'Ranger'], ['Revenant', 'Revenant'], ['Thief', 'Thief'], ['Warrior', 'Warrior']])) %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form' %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Characters</h1>

<p><span class="glyphicon glyphicon-plus-sign"></span><%= link_to ' New Character', new_character_path %></p>

<% @characters.each do |character| %>
  <div class="col-md-3 col-xs-12 char-box">
  <div class="charac">
    <p class="charac-name"><%= character.name %></p>
    <div class="col-md-6 col-xs-12 img-box">
      <%= image_tag(character.image_url, class: "img-responsive charac-img" ) %>
    </div>
    <div class="col-md-6 col-xs-12">
      <br>
      <p class="info">
        <strong>Level: </strong><%= character.level %> <br>
        <strong>Profession: </strong><%= character.profession %> <br>
        <strong>Race: </strong><%= character.race %> <br>
      </p>
    </div>
    <div class="col-md-2 col-xs-2 item-options show-op">
      <%= link_to 'Show', character %>
    </div>
    <div class="col-md-2 col-xs-2 item-options edit-op">
      <%= link_to 'Edit', edit_character_path(character) %>
    </div>
    <div class="col-md-2 col-xs-2 item-options delete-op">
      <%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    <br>
  </div>
  </div>
<% end %>

app/views/characters/new.html.erb
<h1>New Character</h1>

<%= render 'form' %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <h1><%= @character.name %></h1>
  <h3>Level <%= @character.level %> | <%= @character.profession %></h3>


  <div class="col-md-4 col-xs-12 img-box">
    <%= image_tag(@character.image_url, class: "img-responsive charac-img" ) %>
  </div>
  <div class="col-md-8 col-xs-12 info">
    <p><strong>Race:</strong> <%= @character.race %></p>
    <p><strong>Gender:</strong> <%= @character.gender %></p>
    <hr>
    <p><strong>Description</strong></p>
    <p><%= @character.description %></p>
  </div>
</div>

<br>
<br>

<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My GW2 Characters</title>
  
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Josefin+Sans">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>

<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button><!-- end button -->
      <div class="brandName navbar-brand">
        <a href="#">My Guild Wars 2 Characters</a>
      </div><!-- end projectName -->
    </div><!-- end navbar-header -->
    
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <li><a href="/characters">All Characters</a></li>
        <li><a href="#">About Me</a></li>
      </ul>
    </div><!-- end navbar-collapse -->
  </div><!-- end navbar container -->
</nav><!-- end navbar -->

<%= yield %>

<footer class="footer navbar navbar-default navbar-fixed-bottom">
  <div class="container-fluid">
    <p class="navbar-text pull-left text-muted" id="footer-text">&copy; 2017 Janelle Hilliard</p>
  </div>
</footer>
</body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/characters.html.erb
<h1>StaticPages#characters</h1>
<p>Find me in app/views/static_pages/characters.html.erb</p>

app/views/static_pages/index.html.erb
<h1>My GW2 Character Website</h1>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <% @featured_characters.each_with_index do |character, i| %>
      <li data-target="#carousel-example-generic" data-slide-to="<%= i %>" class="<%= "active" if character == @featured_characters.first %>"></li>
    <% end %>
    
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <% @featured_characters.each do |character| %>
      <div class="item <%= " active" if character == @featured_characters.first %>">
        <%= image_tag(character.image_url) %>
        <div class="carousel-caption">
          <p class="name"><%= character.name %></p>
          <p class="prof"><%= character.profession %></p>
        </div>
      </div>
    <% end %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>